In [14]:
import os
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
df = pd.read_csv("C://Users//koh18//Downloads//TNL Project//cleaned_training_dataset_normal.csv")

print("Dataset Shape:", df.shape)

df.head()

Dataset Shape: (1139, 8)

,domain,topic,video_title,video_url,comment,sentiment,comment_en,clean_comment
0,AI,AI Hub,Malaysia as a generative AI hub - Interview wi...,https://www.youtube.com/watch?v=LZSUz-SuYgI,He knows what he is doing 👍👍 the good truth an...,Positive,He knows what he's doing 👍👍 the truth and the ...,know thumb thumb truth stronghold
1,AI,AI Hub,Malaysia as a generative AI hub - Interview wi...,https://www.youtube.com/watch?v=LZSUz-SuYgI,Industrial Master Plan\nShould be Target Certa...,Neutral,The industrial master plan should be targeted ...,industrial master plan targeted certain area e...
2,AI,AI Hub,Malaysia as a generative AI hub - Interview wi...,https://www.youtube.com/watch?v=LZSUz-SuYgI,Very intelligent minister,Positive,Very intelligent minister,intelligent minister
3,AI,AI Hub,Malaysia as a generative AI hub - Interview wi...,https://www.youtube.com/watch?v=LZSUz-SuYgI,The beginning of Malaysia AI Artificial Intell...,Positive,The beginning of Malaysia's AI (Artificial Int...,beginning malaysia ai artificial intelligence ...
4,AI,AI Hub,Malaysia as a generative AI hub - Interview wi...,https://www.youtube.com/watch?v=LZSUz-SuYgI,Lagi MANTAP MALAYSIA..,Positive,Malaysia is really awesome again..,malaysia really awesome

In [16]:
print(df["sentiment"].value_counts())

sentiment
Positive    387
Negative    378
Neutral     374
Name: count, dtype: int64

In [17]:
df[["comment", "clean_comment"]].head(20)

,comment,clean_comment
0,He knows what he is doing 👍👍 the good truth an...,know thumb thumb truth stronghold
1,Industrial Master Plan\nShould be Target Certa...,industrial master plan targeted certain area e...
2,Very intelligent minister,intelligent minister
3,The beginning of Malaysia AI Artificial Intell...,beginning malaysia ai artificial intelligence ...
4,Lagi MANTAP MALAYSIA..,malaysia really awesome
5,Congratulations for your ratification of WTO l...,congratulation ratification wto law
6,Mantap..👍😊👍🇲🇾,awesome
7,"We need results, not headlines.",need result headline
8,There are bigger issues to solve first.,bigger issue solve first
9,I don't think this is enough.,think enough
10,Hopefully this project is managed properly.,hopefully project managed properly
11,Too much hype already.,much hype already
12,Malaysia still has a long way to go.,malaysia still long way go
13,Hope this won't be delayed again.,hope delayed
14,Still waiting to see real progress.,still waiting see real progress
15,Don't expect miracles overnight.,expect miracle overnight
16,I'll believe it when I see the results.,believe see result
17,Mantap,awesome
18,Can't imagine if menteri formula is being inte...,imagine minister formula interviewed
19,Kecerdasan Buatan (Artificial intelligence - A...,artificial intelligence ai could artificial in...

In [18]:
X = df["clean_comment"]

y = df["sentiment"]

In [19]:
#Train/Test Split
#Stratified Sampling
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
    
)
print("Training Samples:", len(X_train))
print("Testing Samples :", len(X_test))

Training Samples: 911
Testing Samples : 228

In [20]:
print("Training Distribution")
print(y_train.value_counts())

print("\nTesting Distribution")
print(y_test.value_counts())

Training Distribution
sentiment
Positive    310
Negative    302
Neutral     299
Name: count, dtype: int64

Testing Distribution
sentiment
Positive    77
Negative    76
Neutral     75
Name: count, dtype: int64

In [21]:
#Create TF-IDF Vectorizer
tfidf = TfidfVectorizer(
    max_features=100000,
    min_df=1,
    max_df=0.90,
    ngram_range=(1,2),
    sublinear_tf=True
)

In [22]:
#Fit TF-IDF
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [23]:
print("Training Matrix:", X_train_tfidf.shape)
print("Testing Matrix :", X_test_tfidf.shape)

Training Matrix: (911, 14242)
Testing Matrix : (228, 14242)

In [24]:
print("Vocabulary Size:", len(tfidf.vocabulary_))

Vocabulary Size: 14242

In [25]:
feature_names = tfidf.get_feature_names_out()
print(feature_names[:50])

['aamiin' 'aamiin yra' 'abandon' 'abandon look' 'abandoned'
 'abandoned left' 'abandoned palm' 'abandoned project' 'abelwoo'
 'abelwoo government' 'ability' 'ability understand' 'able' 'able acquire'
 'able better' 'able build' 'able diversify' 'able enter' 'able hold'
 'able learn' 'able produce' 'able replaced' 'able run' 'able support'
 'abroad' 'abroad frequently' 'absolutely' 'absolutely actually'
 'absolutely good' 'absolutely right' 'absolutely would' 'abundant'
 'abundant water' 'abuse' 'abuse power' 'academic' 'academic bad'
 'academic came' 'academy' 'academy program' 'accelerate'
 'accelerate technological' 'accept' 'accept move' 'acceptable'
 'acceptable salary' 'accepts' 'accepts smiling' 'access' 'access support']

In [26]:
os.makedirs("TF-IDF file", exist_ok=True)
joblib.dump(tfidf, "TF-IDF file/tfidf_vectorizer.pkl")
print("TF-IDF vectorizer saved.")

TF-IDF vectorizer saved.

In [27]:
os.makedirs("Feature Representations", exist_ok=True)
joblib.dump(X_train_tfidf, "Feature Representations/X_train_tfidf.pkl")
joblib.dump(X_test_tfidf, "Feature Representations/X_test_tfidf.pkl")

joblib.dump(y_train, "Feature Representations/y_train.pkl")
joblib.dump(y_test, "Feature Representations/y_test.pkl")

print("Training and testing datasets saved.")

Training and testing datasets saved.

In [28]:
print("="*60)
print("Feature Engineering Completed")
print("="*60)
print(f"Training Samples : {X_train_tfidf.shape[0]}")
print(f"Testing Samples  : {X_test_tfidf.shape[0]}")
print(f"Features         : {X_train_tfidf.shape[1]}")

============================================================
Feature Engineering Completed
============================================================
Training Samples : 911
Testing Samples  : 228
Features         : 14242